### ISSUE TITLE
Scroll bar on examples is always displayed on Chrome for Windows

### ISSUE THREAD

**Issue by gustavobmichel** [kentcdodds/react-workshop-app#12]
What happened:
![epic-react-bug](https://user-images.githubusercontent.com/14951413/94844630-6f6ae480-0416-11eb-8609-74ab7d11ca71.png)

Problem description:
When opening the workshop exercises, a scrollbar is always displayed on the exercise page and when clicking on Extra Credit, even when the scrollbar is not needed. I am using Chrome 85 on Windows 10.

Suggested solution:
Add overflow-y: auto for the exercise Sandbox and overflow-x: auto for ExtraCreditTabs. I do not have a MacOS so not sure if that would not give a different outcome for Macs.

**Comment by kentcdodds** [comment]
Thanks for suggesting this! I'm guessing your suggestion works for windows, so I'll give it a shot on my mac and if it works I'll go for it :)

**Comment by kentcdodds** [comment]
That worked! Thanks :)

**Comment by kentcdodds** [comment]
@all-contributors please add @gustavobmichel for bugs
