### ISSUE TITLE
Open a new tab for the isolated exercise/final/credit page

### ISSUE THREAD

**Issue by Joyancefa** [kentcdodds/react-workshop-app#13]
### Versions

- `@kentcdodds/react-workshop-app` version: ^2.16.4
- `node` version: v12.18.3
- `npm` version: 6.14.6

### Relevant code or config

```javascript
<div
    css={{
    display: 'flex',
    justifyContent: 'flex-end',
    width: '100%',
    }}
>
    <a
    style={{
        display: 'flex',
        justifyContent: 'flex-end',
        padding: '1rem',
        textDecoration: 'none',
    }}
    href={isolatedPath}
    >
    <RiExternalLinkLine css={{marginRight: '0.25rem'}} />{' '}
    {isolatedPathLinkContent}
    </a>
 </div>
```

### Problem description:
I am currently following the EpicReact.dev course and when I `open exercise/final/extra credit on isolated page`, I was expecting when clicking on the button to open a new tab (especially with the icon used).

<img width="641" alt="Screenshot 2020-10-01 at 19 38 03" src="https://user-images.githubusercontent.com/64249481/94843960-c1633880-041d-11eb-9e2d-6b62692e126b.png">

### Suggested solution: 

Add `target="_blank" rel="noopener"` in the `a` element.

**Comment by kentcdodds** [comment]
Good idea! Would you be willing to [make a pull request](http://makeapullrequest.com) for that?

**Comment by Joyancefa** [comment]
Yes! I have just opened a pull request here: https://github.com/kentcdodds/react-workshop-app/pull/15/files

**Comment by kentcdodds** [comment]
Thanks! Merged :)
