### ISSUE TITLE
Production deploys messes up sorting of final solution and extra credit

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/react-workshop-app#30]
This only happens when we deploy:

![image](https://user-images.githubusercontent.com/1500684/95585888-1e05bb00-09fd-11eb-8174-3f48bba28a0a.png)

Running the dev server works fine and building locally works fine as well. It's only when we actually deploy to production that we have problems 🤔

**Comment by kentcdodds** [comment]
I figured it out. Node v10 has a weird sorting issue. Not sure what it is, so I just updated netlify to use node 14.

I realize this means that currently our sorting will be wrong for Node v10 users and I'd love to get that fixed, but I've got too many things on my plate to deal with that right now.

**Comment by Aprillion** [comment]
Sorry if my change caused troubles, I will have a look in Node 10..

**Comment by kentcdodds** [comment]
No worries. I love your changes. Thanks 😁

--- original message ---
On Fri, Oct 9 at 03:07 PM, <notifications@github.com> Peter Hozák wrote:



Sorry if my change caused troubles, I will have a look in Node 10..

—

You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---
