### ISSUE TITLE
Unable to open newly created files on isolated page without server restart

### ISSUE THREAD

**Issue by belev** [kentcdodds/react-workshop-app#36]
- `@kentcdodds/react-workshop-app` version: 2.19.5
- `node` version: 12.16.1
- `npm` version: 6.14.5

#### What you did:

Create new file in `exercise` to implement the solution for the extra credit tasks - e.g. `01.extra-1.html`.

#### What happened:

Unable to see it on isolated page without restarting the server - e.g. `http://localhost:3000/isolated/exercise/01.extra-1.html`

#### Problem description:

The newly created files are not automatically tracked and can't be accessed on isolated page.

#### Suggested solution:

It would be nice to be able to access the newly created files for solutions on isolated pages without server restart.

**Comment by kentcdodds** [comment]
I'm afraid this is impossible :-(

**Comment by belev** [comment]
A bit unfortunate but it's such a small thing compared to all of the awesome workshops 🙌. Thank you for your response.
