### ISSUE TITLE
Handle `export {App}`, not only `export default App` from exercises

### ISSUE THREAD

**Issue by Aprillion** [kentcdodds/react-workshop-app#39]
Workshop exercises (and final) have to use default exports to support `React.lazy` (which can only render a default export) in https://github.com/kentcdodds/react-workshop-app/blob/7a5504500fc75c7275933ca1e16bc30fab45bd6e/src/index.tsx#L66

However, it can be confusing if someone tries to import a function that is not exported, e.g. `import Greeting from ...` while the exported function is `export default App` - see https://discord.com/channels/715220730605731931/759594515668926514/802835578398965780

I noticed that Kent prefers named exports anyway and it should be possible hammer the Promise with `import().then( ??? )` into a shape supported by React.lazy, so that the exercises can be rewritten into `export {App}` => I will try to make PR and we can discuss whether such hack is useful enough..

I'm thinking to support following in exercise files:
1. `export {App}` and/or `export function App` as the new standard
2. `export default Whatever` for gradual transition... (maybe with a `console.warn` in Jest, as a gentle reminder between TypeScriptifying and re-recording videos)
3. if there is no default export and no App, render an error message that a component called `App` has to be exported from the exercise file

**Comment by Aprillion** [comment]
I was able to make the unit tests green, but `npm run dev`  does not work on Windows for me - probably due to unfinished migration of `codegen.macro` to typesript (the generated JS file contains `require('./load-files')` which works fine when executed directly in Node in the `dist` directory, but seems to be problematic via codegen for unknown reason).

```js
./src/index.js
Error: C:\Users\Peter\git\react-workshop-app\example\react-fundamentals\src\index.js: codegen.macro:
 Cannot find module './load-files'

Require stack:
- C:\Users\Peter\git\react-workshop-app\dist\get-app-info.js
- C:\Users\Peter\git\react-workshop-app\dist\codegen.js
- C:\Users\Peter\git\react-workshop-app\codegen.js
- C:\Users\Peter\git\react-workshop-app\example\react-fundamentals\src\index.js
- C:\Users\Peter\git\react-workshop-app\example\react-fundamentals\node_modules\babel-plugin-codegen\dist\helpers.js
- C:\Users\Peter\git\react-workshop-app\example\react-fundamentals\node_modules\babel-plugin-codegen\dist\replace.js
- C:\Users\Peter\git\react-workshop-app\example\react-fundamentals\node_modules\babel-plugin-codegen\dist\macro.js
- C:\Users\Peter\git\react-workshop-app\example\react-fundamentals\node_modules\babel-plugin-codegen\macro.js
- C:\Users\Peter\git\react-workshop-app\example\react-fundamentals\node_modules\codegen.macro\index.js
- C:\Users\Peter\git\react-workshop-app\example\react-fundamentals\node_modules\babel-preset-react-app\node_modules\babel-plugin-macros\dist\index.js
- C:\Users\Peter\git\react-workshop-app\example\react-fundamentals\node_modules\babel-preset-react-app\create.js
- C:\Users\Peter\git\react-workshop-app\example\react-fundamentals\node_modules\babel-preset-react-app\index.js
- C:\Users\Peter\git\react-workshop-app\example\react-fundamentals\node_modules\@babel\core\lib\config\files\plugins.js
- C:\Users\Peter\git\react-workshop-app\example\react-fundamentals\node_modules\@babel\core\lib\config\files\index.js
- C:\Users\Peter\git\react-workshop-app\example\react-fundamentals\node_modules\@babel\core\lib\index.js
- C:\Users\Peter\git\react-workshop-app\example\react-fundamentals\node_modules\rollup-plugin-babel\dist\rollup-plugin-babel.cjs.js
- C:\Users\Peter\git\react-workshop-app\example\react-fundamentals\node_modules\workbox-build\build\lib\bundle.js
- C:\Users\Peter\git\react-workshop-app\example\react-fundamentals\node_modules\workbox-webpack-plugin\build\generate-sw.js
- C:\Users\Peter\git\react-workshop-app\example\react-fundamentals\node_modules\workbox-webpack-plugin\build\index.js
- C:\Users\Peter\git\react-workshop-app\example\react-fundamentals\node_modules\react-scripts\config\webpack.config.js
- C:\Users\Peter\git\react-workshop-app\example\react-fundamentals\node_modules\react-scripts\scripts\start.js
Learn more: https://www.npmjs.com/package/codegen.macro
```

**Comment by kentcdodds** [comment]
Yeah, if the setup script fails then dev will definitely fail. It's kind of a weird setup 😅
