### ISSUE TITLE
"edit docs" button next to "Your Notes" is confusing

### ISSUE THREAD

**Issue by Aprillion** [kentcdodds/react-workshop-app#41]
### Problem description:

Each workshop has an "edit docs" button that points to the original Kent's repository, for simplified PR creation if a user will notice a typo or other problem with the exercise MD file.

However, a new section was recently added for "Your Notes" => encouraging users to write their own notes in the MD file inside own git repo:

![image](https://user-images.githubusercontent.com/1087670/111033304-d43c5900-8410-11eb-85c1-22d41132367f.png)

This combination was confusing for me, I thought the Edit button will navigate to the MD file in my editor, e.g. with some version of `file:///...` (which is blocked by browsers for security reason) or `vscode://...` (which would need some setup like in https://github.com/shengyou/vscode-handler).

### Suggested solutions:

* a) improve tooltip to clarify that the 2 features are not related (e.g. `edit docs (in the original repo, e.g. to fix typos)`)
* b) delete the button or move it to the bottom of the page, close to feedback form link
* c) consider whether it would make sense to have a button to open the MD file in local editor (with new instructions for users how to set it up)

**Comment by kentcdodds** [comment]
Good point. I prefer your first suggestion. Thanks!
