### ISSUE TITLE
Alfred Tip not showing on terminal

### ISSUE THREAD

**Issue by pnadalini** [kentcdodds/react-workshop-app#52]
- `@kentcdodds/react-workshop-app` version: 6.0.1
- `node` version: v16.18.0
- `npm` version: 8.19.2
- OS: macOS, M1 chip

Relevant code or config

```javascript
alfredTip(
    output.getAttribute("role") !== "alert",
    'Add an attribute `role="alert"` to the div to help with screen reader users.',
  )
```

What you did:
Running the react-fundamentals course (exercise `06.extra-2.js`), I didn't add the `alert="role"` in the error message `span`. After running the tests I got the error for the test name, but didn't get the `alfredTip` message.

I ran `npm test`

What happened:
No helpful message appeared, on the integrated vscode terminal nor on the mac terminal.

![image](https://user-images.githubusercontent.com/26207809/203860272-8788ea9b-246f-4450-bac6-f9cdb30b5237.png)

Reproduction repository:

Problem description:

Suggested solution:

**Comment by kentcdodds** [comment]
Hmmm... I just did a fresh install of the workshop repo and got this:

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/1500684/204111527-cad87571-770c-4d39-9252-f0e0029ce953.png">

There was a problem which I fixed 9 days ago. Do you perhaps have an old version of the repo?

**Comment by pnadalini** [comment]
Yeah thank you, pulling the latest version solved it. Although some of your other repos from the course might need an update too, I had the same problem with `react-hooks` repo (this repo is using version 6.0.1).

Looking at your changes to the package-lock in `react-fundamentals` and doing some testing, **6.0.2** has the fix to this issue 👍

**Comment by kentcdodds** [comment]
Fixed! Thank you :)
